#!/usr/bin/env bash
set -e -u -o pipefail

function release() {
    VERSION=$(cat VERSION)
    MAJOR=$(echo $VERSION | cut -d '.' -f1)
    MINOR=$(echo $VERSION | cut -d '.' -f2)
    PATCH=$(echo $VERSION | cut -d '.' -f3)
    case $1 in
        major)
            MAJOR=$(($MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
        minor)
            MINOR=$(($MINOR + 1))
            PATCH=0
            ;;
        patch|*)
            PATCH=$(($PATCH + 1))
            ;;
    esac
    NEWVERSION=$MAJOR.$MINOR.$PATCH
    echo $NEWVERSION > VERSION
    git add .
    git commit -m "release: updating from $VERSION to $NEWVERSION"
}

arg=${1:-patch}
release $arg
